### ISSUE TITLE
Hide Wiki Tab

### ISSUE THREAD

**Issue by verma-kunal** [adarshaacharya/states-nepal#20]
Suggested to hide the Wiki Tab if not being used!!

Screenshot:
![Screenshot 2021-05-28 at 9 40 21 PM](https://user-images.githubusercontent.com/72245772/120012587-4f1f1400-bffd-11eb-86ec-3ccbe47e980a.png)

**Comment by adarshaacharya** [comment]
Thanks @verma-kunal didn't knew this feature exists.

**Comment by verma-kunal** [comment]
No worries! Happy to help 👍
